apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: edu-user-hpa
  namespace : edu-user
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp-deployment
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 30
