apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: edu-goods-hpa
  namespace : edu-goods
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-edu-goods-deployment
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 30
